### ISSUE TITLE
Running multiple cases at the same time and reporting errors: panic: double seq is less than call seq

### ISSUE THREAD

**Issue by kannae97** [agiledragon/gomonkey#162]
Like this:
<img width="896" alt="image" src="https://github.com/agiledragon/gomonkey/assets/60053915/46387e64-2137-4f90-8b63-8a521e3eaa92">

panic: double seq is less than call seq [recovered]
	panic: double seq is less than call seq

**Comment by shenshimin** [comment]
> gomonkey is not concurrent safe, try xgo if you need concurrent safety: https://github.com/xhd2015/xgo

Thank u, bro.

**Comment by agiledragon** [comment]
@kannae97 
This has nothing to do with thread safety. When using sequence patches, ensure the sequence length is at least equal to the number of calls; otherwise, it will panic. Sequence patches emphasize that the return value differs with each call. In this case, the sequence patch length is 1, so using the sequence patch API is meaningless. Using the regular patch API is sufficient since the return value is the same for each call, with no call count limit.
