### ISSUE TITLE
ApplyFunc not working

### ISSUE THREAD

**Issue by changsongl** [agiledragon/gomonkey#34]
````golang
//test/func_test.go
package test

import (
	. "github.com/agiledragon/gomonkey"
	. "github.com/smartystreets/goconvey/convey"
	"testing"
)

func TestGetGroupLastSend(t *testing.T) {
	Convey("Comparing two variables", t, func() {
		num := 333
		ApplyFunc(GetB, func() int {
			return num
		})
		result := GetA()
		So(num, ShouldEqual, result)
	})
}

//test/func.go
package test

func GetA() int {
	return GetB()
}

func GetB() int {
	return 1
}

  Expected: '1'
  Actual:   '333'
  (Should be equal)

````

I am not sure why this is failed. Did I use it in the wrong way?

**Comment by oops-oom** [comment]
Read READ.ME.
>gomonkey fails to patch a function or a member method if inlining is enabled, please running your tests with inlining disabled by adding the command line argument that is -gcflags=-l(below go1.10) or -gcflags=all=-l(go1.10 and above).

**Comment by YYCoder** [comment]
I encountered this issue too, and took an hour to find out why.

I think maybe it's better to add a little explanation in README about what is `inlining` in golang, and how it affects our code, what's the potential problem may happen if we don't add flag `-gcflags=all=-l` to disable it, since I believe many of developers don't know it well.

**Comment by renukamanavalan** [comment]
I encountered this issue too, and took few hours to find out why.

A Bold NOTE, in the doc for [ApplyFunc ](https://pkg.go.dev/github.com/agiledragon/gomonkey/v2#ApplyFunc) will be a *big* help.
